name: "Notify"
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: GitHub App token
        uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: "1786861"
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          repositories: "go.ikura-hamu.work"

      - name: notify
        uses: ikura-hamu/go-import-pages/notify@v0.2.0
        with:
          owner: ikura-hamu
          repo_name: go.ikura-hamu.work
          github_token: ${{ steps.app-token.outputs.token }}
          issue_number: 2
